//! First-run wizard: `/onboarding` command.
//!
//! Creates `~/.oxicode/settings.toml` interactively — prompts for
//! API provider, key, model, and permission mode.

use std::fmt::Write as _;
use std::path::PathBuf;

use super::{CommandContext, CommandOutput, SlashCommand};

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/// Resolve the settings.toml path: `~/.oxicode/settings.toml`.
fn settings_path() -> Option<PathBuf> {
    dirs::home_dir().map(|h| h.join(".oxicode").join("settings.toml"))
}

/// Check whether a minimal settings file already exists.
fn has_existing_config() -> bool {
    settings_path().is_some_and(|p| p.exists())
}

/// Detect current API key from environment variables.
fn detect_api_key() -> Option<(&'static str, String)> {
    if let Ok(key) = std::env::var("ANTHROPIC_API_KEY") {
        if !key.is_empty() {
            return Some(("anthropic", key));
        }
    }
    if let Ok(key) = std::env::var("OPENAI_API_KEY") {
        if !key.is_empty() {
            return Some(("openai", key));
        }
    }
    if std::env::var("OLLAMA_HOST").is_ok() || std::env::var("OLLAMA_BASE_URL").is_ok() {
        return Some(("ollama", String::new()));
    }
    None
}

/// Mask an API key for safe display: `sk-ant-...XXXX`.
fn mask_key(key: &str) -> String {
    if key.len() <= 8 {
        return "****".to_string();
    }
    let prefix = &key[..std::cmp::min(7, key.len())];
    let suffix = &key[key.len() - 4..];
    format!("{prefix}...{suffix}")
}

/// Build quick-start tips after successful setup.
fn quick_start_tips() -> String {
    "Quick-start guide:\n\
     1. Type a prompt to start chatting with the LLM\n\
     2. Use /help to see all available commands\n\
     3. Use /model to switch models mid-conversation\n\
     4. Use /session list to browse past sessions\n\
     5. Use /compact to shrink context when running low"
        .to_string()
}

/// Generate a sample `settings.toml` content.
fn sample_toml(provider: &str, model: &str, permission_mode: &str) -> String {
    let mut toml = String::with_capacity(256);
    let _ = writeln!(toml, "# OxiCode configuration — generated by /onboarding");
    let _ = writeln!(
        toml,
        "# See: https://github.com/nhtera/oxicode#configuration"
    );
    let _ = writeln!(toml);
    let _ = writeln!(toml, "provider = \"{provider}\"");
    let _ = writeln!(toml, "model = \"{model}\"");
    let _ = writeln!(toml, "permission_mode = \"{permission_mode}\"");
    let _ = writeln!(toml);
    let _ = writeln!(
        toml,
        "# API key is read from env: ANTHROPIC_API_KEY / OPENAI_API_KEY"
    );
    let _ = writeln!(toml, "# max_tokens = 16384");
    toml
}

/// Default model for each provider.
fn default_model(provider: &str) -> &'static str {
    match provider {
        "openai" => "gpt-4o",
        "ollama" => "llama3.1",
        // anthropic and any unknown provider default to Claude
        _ => "claude-sonnet-4-20250514",
    }
}

// ---------------------------------------------------------------------------
// /onboarding
// ---------------------------------------------------------------------------

/// `/onboarding` — first-run configuration wizard.
pub struct OnboardingCommand;

impl SlashCommand for OnboardingCommand {
    fn name(&self) -> &str {
        "onboarding"
    }

    fn description(&self) -> &str {
        "First-run setup wizard (create settings.toml)"
    }

    fn execute(&self, args: &str, _ctx: &CommandContext) -> CommandOutput {
        let skip_validation = args.contains("--skip-validation");

        // 1. Already configured?
        if has_existing_config() {
            let key_info = detect_api_key().map_or_else(
                || "No API key detected in environment".to_string(),
                |(p, k)| {
                    if k.is_empty() {
                        format!("Provider: {p} (local)")
                    } else {
                        format!("Provider: {p} | Key: {}", mask_key(&k))
                    }
                },
            );

            return CommandOutput::Message(format!(
                "Already configured!\n\
                 Settings: {}\n\
                 {key_info}\n\n\
                 {}\n\n\
                 Tip: edit settings.toml or use /config to change settings.",
                settings_path()
                    .map(|p| p.display().to_string())
                    .unwrap_or_default(),
                quick_start_tips(),
            ));
        }

        // 2. Not configured — run wizard.
        let mut output = String::with_capacity(1024);

        // ASCII logo
        output.push_str(
            "╔══════════════════════════════════════╗\n\
             ║  OxiCode — First-Run Setup Wizard    ║\n\
             ╚══════════════════════════════════════╝\n\n",
        );

        // Detect provider from environment
        let (provider, key) = detect_api_key().unwrap_or(("anthropic", String::new()));
        let model = default_model(provider);

        if key.is_empty() && provider != "ollama" {
            output.push_str(
                "No API key detected.\n\
                 Set one of these environment variables:\n\
                 - ANTHROPIC_API_KEY (for Claude)\n\
                 - OPENAI_API_KEY (for GPT models)\n\
                 - OLLAMA_HOST (for local Ollama)\n\n",
            );
        } else {
            let _ = writeln!(output, "Detected provider: {provider}");
            if !key.is_empty() {
                let _ = writeln!(output, "API key: {}", mask_key(&key));
            }
            let _ = writeln!(output, "Default model: {model}");
            output.push('\n');
        }

        // Validation check
        if !skip_validation && !key.is_empty() {
            output.push_str("API key validation: pending (will test on first request)\n");
        } else if skip_validation {
            output.push_str("API key validation: skipped (--skip-validation)\n");
        }

        // Permission modes explanation
        output.push_str(
            "\nPermission modes:\n\
             - default   — auto-allow reads, ask for writes\n\
             - bypass    — trust everything (use with caution)\n\
             - approval  — ask for every non-readonly operation\n\n",
        );

        let permission_mode = "default";

        // Attempt to create settings file
        match settings_path() {
            Some(path) => {
                // Create directory
                if let Some(parent) = path.parent() {
                    if let Err(e) = std::fs::create_dir_all(parent) {
                        return CommandOutput::Error(format!("Failed to create ~/.oxicode/: {e}"));
                    }
                }

                let content = sample_toml(provider, model, permission_mode);
                match std::fs::write(&path, &content) {
                    Ok(()) => {
                        let _ = writeln!(output, "Created: {}\n", path.display());
                        output.push_str(&quick_start_tips());
                    }
                    Err(e) => {
                        return CommandOutput::Error(format!("Failed to write settings.toml: {e}"));
                    }
                }
            }
            None => {
                return CommandOutput::Error("Could not determine home directory.".to_string());
            }
        }

        CommandOutput::Message(output)
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::Arc;

    fn make_ctx() -> CommandContext {
        CommandContext {
            state_store: Arc::new(oxicode_state::StateStore::default()),
            model: "test".to_string(),
            provider_name: "test".to_string(),
            session_id: "test".to_string(),
        }
    }

    #[test]
    fn test_mask_key_long() {
        assert_eq!(mask_key("sk-ant-abcdef1234567890"), "sk-ant-...7890");
    }

    #[test]
    fn test_mask_key_short() {
        assert_eq!(mask_key("abc"), "****");
    }

    #[test]
    fn test_default_model_anthropic() {
        // anthropic falls through to the default arm
        assert_eq!(default_model("anthropic"), "claude-sonnet-4-20250514");
        assert_eq!(default_model("unknown"), "claude-sonnet-4-20250514");
    }

    #[test]
    fn test_default_model_openai() {
        assert_eq!(default_model("openai"), "gpt-4o");
    }

    #[test]
    fn test_default_model_ollama() {
        assert_eq!(default_model("ollama"), "llama3.1");
    }

    #[test]
    fn test_sample_toml_contains_fields() {
        let toml = sample_toml("anthropic", "claude-sonnet-4-20250514", "default");
        assert!(toml.contains("provider = \"anthropic\""));
        assert!(toml.contains("model = \"claude-sonnet-4-20250514\""));
        assert!(toml.contains("permission_mode = \"default\""));
    }

    #[test]
    fn test_quick_start_tips_not_empty() {
        let tips = quick_start_tips();
        assert!(tips.contains("/help"));
        assert!(tips.contains("/model"));
    }

    #[test]
    fn test_onboarding_command_metadata() {
        let cmd = OnboardingCommand;
        assert_eq!(cmd.name(), "onboarding");
        assert!(!cmd.description().is_empty());
    }

    #[test]
    fn test_onboarding_command_executes() {
        // This test may create settings.toml or say "already configured".
        // Both are valid outcomes.
        let cmd = OnboardingCommand;
        let ctx = make_ctx();
        let output = cmd.execute("--skip-validation", &ctx);
        match output {
            CommandOutput::Message(msg) | CommandOutput::Error(msg) => assert!(!msg.is_empty()),
            _ => panic!("Expected message or error"),
        }
    }
}
