pub mod app;
pub mod events;
pub mod ghost_completion;
pub mod keybindings;
pub mod paste_detector;
pub mod prompt_suggestions;
pub mod streaming_markdown;
pub mod themes;
pub mod tips_service;
pub mod vim_mode;
pub mod vim_text_objects;
pub mod widgets;

pub use app::App;
pub use events::{CoreEvent, UiEvent};
pub use keybindings::KeybindingRegistry;
pub use prompt_suggestions::{suggest_prompts, PromptSuggestion};
pub use themes::{get_theme, ThemePalette};
pub use tips_service::TipsService;
pub use vim_mode::VimState;
pub use widgets::command_autocomplete::SlashCommandMeta;
