//! Workflow generator — create `.github/workflows/oxicode.yml` content.
//!
//! Generates a GitHub Actions workflow that runs OxiCode in CI/CD.

/// Generate the OxiCode GitHub Actions workflow YAML content.
pub fn generate_oxicode_workflow(default_branch: &str) -> String {
    format!(
        r#"# OxiCode CI — auto-generated by /install-github-app
name: OxiCode Review

on:
  push:
    branches: ["{default_branch}"]
  pull_request:
    branches: ["{default_branch}"]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  oxicode-review:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install OxiCode
        run: |
          curl -fsSL https://raw.githubusercontent.com/nhtera/oxicode/main/scripts/install.sh | bash
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Run OxiCode Review
        env:
          ANTHROPIC_API_KEY: ${{{{ secrets.ANTHROPIC_API_KEY }}}}
        run: |
          oxicode -p "Review the changes in this PR. Focus on:
            1. Code quality and best practices
            2. Potential bugs or security issues
            3. Performance concerns
            Provide actionable feedback." --output json
"#
    )
}

/// Generate a minimal workflow (no review, just lint check).
pub fn generate_minimal_workflow(default_branch: &str) -> String {
    format!(
        r#"# OxiCode Lint — auto-generated by /install-github-app
name: OxiCode Lint

on:
  pull_request:
    branches: ["{default_branch}"]

permissions:
  contents: read

jobs:
  oxicode-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - name: Install OxiCode
        run: |
          curl -fsSL https://raw.githubusercontent.com/nhtera/oxicode/main/scripts/install.sh | bash
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Lint Check
        env:
          ANTHROPIC_API_KEY: ${{{{ secrets.ANTHROPIC_API_KEY }}}}
        run: |
          oxicode -p "Check this codebase for lint issues and report them concisely." --output json
"#
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_workflow_contains_branch() {
        let workflow = generate_oxicode_workflow("main");
        assert!(workflow.contains("main"));
        assert!(workflow.contains("OxiCode Review"));
        assert!(workflow.contains("actions/checkout"));
    }

    #[test]
    fn test_generate_workflow_custom_branch() {
        let workflow = generate_oxicode_workflow("develop");
        assert!(workflow.contains("develop"));
    }

    #[test]
    fn test_generate_workflow_has_api_key_secret() {
        let workflow = generate_oxicode_workflow("main");
        assert!(workflow.contains("ANTHROPIC_API_KEY"));
        assert!(workflow.contains("secrets.ANTHROPIC_API_KEY"));
    }

    #[test]
    fn test_generate_workflow_has_permissions() {
        let workflow = generate_oxicode_workflow("main");
        assert!(workflow.contains("pull-requests: write"));
        assert!(workflow.contains("contents: read"));
    }

    #[test]
    fn test_generate_minimal_workflow() {
        let workflow = generate_minimal_workflow("main");
        assert!(workflow.contains("OxiCode Lint"));
        assert!(workflow.contains("main"));
        assert!(!workflow.contains("pull-requests: write"));
    }

    #[test]
    fn test_workflow_is_valid_yaml_structure() {
        let workflow = generate_oxicode_workflow("main");
        // Basic structure checks (not full YAML parsing — no yaml crate dep).
        assert!(workflow.contains("name:"));
        assert!(workflow.contains("on:"));
        assert!(workflow.contains("jobs:"));
        assert!(workflow.contains("steps:"));
        assert!(workflow.contains("runs-on:"));
    }
}
